# Generated by Django 5.0.7 on 2024-10-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_alter_book_copies_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveIntegerField(),
        ),
    ]
