# Generated by Django 5.0.7 on 2024-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0006_remove_userprofile_is_admin_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='overdue_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loan_duration',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
