# Generated by Django 5.0.7 on 2024-10-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0009_alter_userprofile_loan_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user']},
        ),
    ]
