# Generated by Django 5.0.7 on 2024-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0010_alter_book_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
