"""
Django settings for library_management_system project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is required!")

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for local development, set to False explicitly in production
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

# Security: Configure ALLOWED_HOSTS for production
ALLOWED_HOSTS = []
allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]

# Always add localhost and 127.0.0.1 in DEBUG mode
if DEBUG:
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])

# Auto-detect Render deployment and add Render hostname
# Priority: Custom domain (from ALLOWED_HOSTS env) > RENDER_EXTERNAL_URL > Fallback
render_external_url = os.getenv("RENDER_EXTERNAL_URL", "")
if os.getenv("RENDER") or render_external_url:
    # Render sets RENDER=true and provides environment variables
    render_service_name = os.getenv("RENDER_SERVICE_NAME", "")
    
    if render_external_url:
        # Extract hostname from URL (e.g., https://api.yourdomain.com -> api.yourdomain.com)
        # or https://library-backend-xxxx.onrender.com -> library-backend-xxxx.onrender.com
        from urllib.parse import urlparse
        parsed = urlparse(render_external_url)
        if parsed.hostname:
            ALLOWED_HOSTS.append(parsed.hostname)
            # Also add without port if it was included
            if ':' in parsed.hostname:
                ALLOWED_HOSTS.append(parsed.hostname.split(':')[0])
            # For custom domains, also add www variant if not already present
            if not parsed.hostname.startswith('www.') and '.' in parsed.hostname:
                domain_parts = parsed.hostname.split('.')
                if len(domain_parts) >= 2:
                    # Add www variant for custom domains (not for .onrender.com)
                    if not parsed.hostname.endswith('.onrender.com'):
                        www_host = 'www.' + parsed.hostname
                        if www_host not in ALLOWED_HOSTS:
                            ALLOWED_HOSTS.append(www_host)
    
    # Note: In production, you MUST set ALLOWED_HOSTS explicitly via environment variable
    # Auto-detection is disabled for security - set ALLOWED_HOSTS in Render dashboard

# Remove duplicates while preserving order
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))

# Safety check: In production (DEBUG=False), ALLOWED_HOSTS must be set
# But allow Render deployments to proceed with auto-detected hosts
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError(
        "ALLOWED_HOSTS environment variable must be set in production! "
        "Set it to your domain(s), e.g., 'yourdomain.com,www.yourdomain.com'. "
        "If deploying on Render, the hostname should be automatically detected, "
        "but you can also set it explicitly in the Render dashboard."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'library_api',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'library_api'/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME", ""),
        'USER': os.getenv("DB_USER", ""),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
        'OPTIONS': {
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
    }
}

# Validate database configuration in production
if not DEBUG:
    db_config = DATABASES['default']
    missing_vars = []
    if not db_config['NAME']:
        missing_vars.append('DB_NAME')
    if not db_config['USER']:
        missing_vars.append('DB_USER')
    if not db_config['PASSWORD']:
        missing_vars.append('DB_PASSWORD')
    
    if missing_vars:
        raise ValueError(
            f"Database configuration is incomplete! Missing: {', '.join(missing_vars)}. "
            "Please set these environment variables in Render dashboard."
        )
    
    # Log database connection info (without password) for debugging
    import logging
    logger = logging.getLogger(__name__)
    logger.info(f"Database configured: {db_config['NAME']}@{db_config['HOST']}:{db_config['PORT']} (user: {db_config['USER']})")


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'min_length': 8,
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = os.getenv("USE_I18N", "True").lower() in ("true", "1", "yes")
USE_TZ = os.getenv("USE_TZ", "True").lower() in ("true", "1", "yes")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories for static files (only if they exist)
STATICFILES_DIRS = []
static_dir = BASE_DIR / 'static'
if static_dir.exists():
    STATICFILES_DIRS.append(static_dir)

# WhiteNoise for static files in production
# WhiteNoise will automatically serve files from STATIC_ROOT
# No special storage backend needed - WhiteNoise middleware handles it
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find static files
WHITENOISE_ROOT = STATIC_ROOT  # Root directory for static files
WHITENOISE_AUTOREFRESH = False  # Don't auto-refresh in production
WHITENOISE_MANIFEST_STRICT = False  # Don't fail if manifest is missing


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100, #I have set the Limit Offset Pagination to 100 you never know
    'DEFAULT_AUTHENTICATION_CLASSES': ( 
        'rest_framework.authentication.BasicAuthentication', 
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    'DEFAULT_PERMISSION_CLASSES': ( 
        'rest_framework.permissions.AllowAny',  # Changed to AllowAny - individual views can override
    ),
    
    # Custom exception handler to return JSON instead of HTML
    'EXCEPTION_HANDLER': 'library_api.exceptions.custom_exception_handler',
} 

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60 if not DEBUG else 500),  # Shorter in production
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7 if not DEBUG else 1),  # Longer in production
    'ROTATE_REFRESH_TOKENS': True,  # Enhanced security
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_warning': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'library_warning.log',
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'library_error.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_warning', 'file_error'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': True,
        },
        'library_api': {
            'handlers': ['console', 'file_warning', 'file_error'],
            'level': 'INFO' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_warning', 'file_error'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
}

# CORS settings for frontend
# Allow CORS origins from environment variable, or default to localhost for development
cors_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "")
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(",") if origin.strip()]
    # Also add www variants for custom domains
    www_origins = []
    for origin in CORS_ALLOWED_ORIGINS:
        if origin.startswith('https://') and not origin.startswith('https://www.'):
            www_origin = origin.replace('https://', 'https://www.')
            if www_origin not in CORS_ALLOWED_ORIGINS:
                www_origins.append(www_origin)
        elif origin.startswith('http://') and not origin.startswith('http://www.'):
            www_origin = origin.replace('http://', 'http://www.')
            if www_origin not in CORS_ALLOWED_ORIGINS:
                www_origins.append(www_origin)
    CORS_ALLOWED_ORIGINS.extend(www_origins)
else:
    # Default to localhost for development
    if DEBUG:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",  # Vite default port
            "http://127.0.0.1:5173",
        ]
    else:
        # In production, require CORS_ALLOWED_ORIGINS to be set
        # If not set, default to empty list (no CORS allowed)
        # Set CORS_ALLOWED_ORIGINS environment variable with your frontend domain(s)
        if not CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS = []
            import warnings
            warnings.warn(
                "CORS_ALLOWED_ORIGINS is not set in production. "
                "Set CORS_ALLOWED_ORIGINS environment variable with your frontend domain(s).",
                UserWarning
            )

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Security settings - Enable in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # Development settings
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

SESSION_COOKIE_AGE = 86400  # 1 day

# Email Configuration
# For production, set these environment variables:
# EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend' (auto-detected)
# EMAIL_HOST: your SMTP server (e.g., 'smtp.gmail.com')
# EMAIL_PORT: SMTP port (587 for TLS recommended, 465 for SSL) - defaults to 587 (TLS)
# EMAIL_USE_TLS: 'True' or 'False' - defaults to 'True' (TLS - recommended)
# EMAIL_USE_SSL: 'True' or 'False' - defaults to 'False' (use TLS instead)
# NOTE: Port 587 with TLS is more reliable and less likely to be blocked by hosting providers
# EMAIL_HOST_USER: your email address
# EMAIL_HOST_PASSWORD: your email password
# DEFAULT_FROM_EMAIL: email address to send from
# FRONTEND_URL: frontend URL for password reset links (e.g., 'http://localhost:3000' or 'https://yourdomain.com')

# Email Backend Configuration
# Priority: Brevo API > SMTP > Console
# Brevo API works on Render (uses HTTPS, not SMTP ports)

BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip().strip('"').strip("'")
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip().strip('"').strip("'")
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip().strip('"').strip("'")

# Auto-detect email backend based on configuration
# Prefer Brevo API if API key is set (works on Render)
if BREVO_API_KEY:
    # Use Brevo API backend (works on Render - uses HTTPS)
    EMAIL_BACKEND = os.getenv(
        'EMAIL_BACKEND',
        'library_api.email_backends.BrevoAPIEmailBackend'
    )
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Use SMTP backend if credentials are provided (may not work on Render)
    EMAIL_BACKEND = os.getenv(
        'EMAIL_BACKEND',
        'django.core.mail.backends.smtp.EmailBackend'
    )
else:
    # Use console backend if no credentials (development - emails to terminal)
    EMAIL_BACKEND = os.getenv(
        'EMAIL_BACKEND',
        'django.core.mail.backends.console.EmailBackend'
    )

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')

# Default to port 587 with TLS (more reliable than 465 with SSL on many hosting platforms)
# Port 587 (TLS) is generally more compatible and less likely to be blocked
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))  # Default to 587 (TLS) instead of 465 (SSL)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')  # Default to TLS
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')  # Default to False (use TLS instead)

# Ensure TLS and SSL are not both enabled
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    # If both are set, prefer TLS (more compatible)
    EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@library.com')
DEFAULT_FROM_NAME = os.getenv('DEFAULT_FROM_NAME', 'Library Management System')

# SMTP Connection Timeouts (CRITICAL - prevents worker timeouts)
# These prevent the email send from hanging indefinitely and causing worker timeouts
# Also used for API timeouts (Brevo API)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))  # 10 seconds timeout for email operations

# Frontend URL for password reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Password reset token timeout (in seconds) - default is 3 days
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', '259200'))  # 3 days

